{% set name = "pysoundfile" %}
{% set pypi_name = "soundfile" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 931738a1c93e8684c2d3e1d514ac63440ce827ec783ea0a2d3e4730e3dc58c18

build:
  number: 1
  noarch: python
  script:
    # We are currently building a noarch package, but pysoundfile contains a
    # install-time check for the OS and injects the sf_wchar_open function
    # conditionally. If this variable is not set, opening files on Windows doesn't work
    # Fix coming hopefully with https://github.com/bastibe/python-soundfile/pull/288
    # Original issue on conda-forge: https://github.com/conda-forge/libsndfile-feedstock/issues/14
    - export PYSOUNDFILE_PLATFORM=win32
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - cffi
  run:
    - python >=3.6
    - cffi
    - numpy
    - libsndfile >=1.2

test:
  imports:
    - soundfile

about:
  home: http://pysoundfile.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  dev_url: https://github.com/bastibe/SoundFile

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
    - bmcfee
